### ISSUE TITLE
wildcards

### ISSUE THREAD

**Issue by Yulia88** [tocodeil/unix1-course-examples#102]
Hi

 Im trying to print out all lowercase files and folders, but even after using google  Im unable to print it out
For example:
ls [a-z]* - prints every file and directory, not only lowercase

**Comment by Yulia88** [comment]
Tried also [[:lower:]] 
not working

**Comment by ynonp** [comment]
Ah yes an interesting Ubuntu feature. You can read more about it here:
http://teaching.idallen.org/net2003/06w/notes/character_sets.txt

Basically Ubuntu (and other recent linuxes) use a sort order that mixes lower and upper case letters: AaBbCcDd... etc.

That's why your [a-z] doesn't seem to work: It actually does work but when your linux sees the a-z it translates it to aBbCcDd...Zz

You can change the collation order by running the command: `export LC_ALL=POSIX`. In future lessons we'll learn more about the export syntax and why it works.
