### ISSUE TITLE
תיקיות שמתחילות באותיות גדולות

### ISSUE THREAD

**Issue by Aviyoosh** [tocodeil/unix1-course-examples#15]
echo [A-Z]* isn't displaying Upper cases, keep displaying lower cases.
what's the command?

**Comment by ynonp** [comment]
The command is correct, but I guess your sort collation order is wrong (it happens). You can read more about it here:
http://teaching.idallen.org/net2003/06w/notes/character_sets.txt

The simple solution is in your shell to write `export LC_ALL=POSIX` or `export LC_ALL=C` (both will work). Later in the course we'll learn how to change this permanently

**Comment by vitalipe** [comment]
It happens due to order of characters in a your locale.. [A-Z] means "match anything in that range", but you locale has the following range => ```aAbBcCdDeE........xXyYzZ``` 

note that the file named ```a.text``` will not be matched! because a comes before A :) 
to fix it you can either use what Ynon suggested or this little trick:
```LC_ALL=C bash -c 'echo [A-Z]*'```

you can also "alias" it, to the name for your choice like so:
```alias echo_all_upper="LC_ALL=C bash -c 'echo [A-Z]*'"```
then simply run:
```echo_all_upper```

alias is actually very common in bash, and you can inspect it with the builtin ```type``` command:
```
vitali@Tux:~/$ type ls
ls is aliased to `ls --color=auto'
vitali@Tux:~/$ type echo_all_upper 
echo_all_upper is aliased to `LC_ALL=C bash -c 'echo [A-Z]*''
``` 

let me know if that makes sense to you :)

**Comment by vitalipe** [comment]
after reading @maximus777666's solution I realized that I'm getting old and  completely forgot about [[:upper:]]... and this should just work: ```ls [[:upper:]]``` :smile: 

there are also ```[:lower] [:space:] [:digit:]....``` and more...
to get the complete list just type: ``` man 7 glob```
