### ISSUE TITLE
Ctr+Shift+"+"

### ISSUE THREAD

**Issue by dovron** [tocodeil/unix1-course-examples#3]
למה רק ה + שבאמצע המקלדת עובד כדי להגדיל?
כאשר לוחצים על ה + בצד ימין הכתב לא גדל.

**Comment by vitalipe** [comment]
good question :) it's terminal specific.. in gnome terminal  I believe they did this because they wrap another vte so they didn't want to conflict with it's commands such as ctrl-l (clear screen), but that's only my guess :) 

I use ->  "ctrl shift +/-" or "ctrl shift 0" to rest size...
and there is also -> "ctrl shift t/w" to open/close tabs :)

**Comment by dovron** [comment]
ctrl shift 0 doesn't work :face_with_head_bandage:

**Comment by vitalipe** [comment]
yeah my bad - it's "ctrl 0" :)
