### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by maximus777666** [tocodeil/unix1-course-examples#39]
Hi,

I want to find file/processes in the system that can be run from simple user with root permissions.

like cronjobs, scripts..

Thanks!

**Comment by vitalipe** [comment]
that's a great question! :) the information that you seek is in the file system.. 

here's what we're looking for:
- files not directories
- setuid or  setgid permission flag (that makes you run the script with the permissions of the owner)
- that are readable & executable by you (that means other or your group)
- files that are owned by root, this is important because if it's owned my other user the process won't get root permissions (you will get the permissions of that user)

the ```find``` command is our here here :) it has TONS of options!

```-type f ``` we care only for files
```-perm "/6000"```  the "/" means match anything that is set -> i,e 4??? and 2???    
```-user root``` owned by root, 

putting this together: 
```find / -perm "/6000" -user root -type f```
this should do the job.. 

it's not perfect because there a few edge cases that I can think of, here's one:

the file must be readable & executable by you (other or the group), otherwise you won't be able to do anything so /6005 should do the job right? not really! because if the group matches your current group "group permissions" will apply here!

check this:
```
vitali@Tux:~$ ls -lh /bin/ping
-rwsr-xr-x 1 root root 44K מאי  7  2014 /bin/ping

########################## THIS IS THE KEY PART - notice that I changed the group ####
vitali@Tux:~$ sudo chown root.vitali /bin/ping
#############################################################################
vitali@Tux:~$ sudo chmod 4705 /bin/ping #let's take away group permissions

vitali@Tux:~$ ping 4.2.2.2
bash: /bin/ping: Permission denied

vitali@Tux:~$ sudo chmod 4750 /bin/ping #now let's take away other permissions
vitali@Tux:~$ ping 4.2.2.2
PING 4.2.2.2 (4.2.2.2) 56(84) bytes of data.
64 bytes from 4.2.2.2: icmp_seq=1 ttl=53 time=90.5 ms
64 bytes from 4.2.2.2: icmp_seq=2 ttl=53 time=83.6 ms
^C
--- 4.2.2.2 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 83.678/87.116/90.555/3.451 ms

vitali@Tux:~$ ls -lh /bin/ping
-rwsr-x--- 1 root vitali 44K מאי  7  2014 /bin/ping
vitali@Tux:~$ 
```

there are a few other, which I'm not gonna go into details now, but feel free to ask me next 
week when we'll have a meetup! and if you didn't understand something don't worry!
 just catch up with me and I'll explain in details  :)

**Comment by vitalipe** [comment]
oh and one more thing! setuid won't work on scripts! because it changes privileges not the environment, I know it sound cryptic if you're didn't do shell scripting.. but just know that setuid 
works only on binaries like ```ping su sudo...```  :)

**Comment by maximus777666** [comment]
Thanks for the answer! have a nice day!

**Comment by vitalipe** [comment]
@maximus777666 u2 :)
