### ISSUE TITLE
system monitor and "appstore"

### ISSUE THREAD

**Issue by nmilgalter** [tocodeil/unix1-course-examples#6]
Hello
1.
I can't find how to open "System Monitor" like we have in mac. (Task Manger)

2.
in the new installed vm, I have internet connection
but, "Ubuntu Software" deosn't show me anything...

**Comment by vitalipe** [comment]
I think that there is a gui for that... I'm not using it  - partly because my Linux beard is too cool for GUIs! :smiley: but mainly because all the power of *nix systems is in the command line... 


there is a awesome tool called "htop", or atop (or the classical top if you really want..) either one is ok :) 

to install htop:
```sudo apt-get install htop```

about the software center - it's a gui wrapper around "apt-get" (the debian package manager), 
so try to run:
``` apt-get update #should download the package index ``` 

and see if you encounter problems.. :beers:

**Comment by nmilgalter** [comment]
Thanks Vitali!!

htop - awesome!

sodu apt-get update executed sucessfuly but now my Ubuntu Software crashes after few seconds :(
any ideas?

Thanks
Noam M.

**Comment by nmilgalter** [comment]
Ubuntu Software is working now please ignore my last comment.
Thanks
Noam M.

**Comment by vitalipe** [comment]
you're welcome! :) 

there are tons of sweet admin tools in this eco-system - 
especially if you're in to networks/security [check this out](https://kkovacs.eu/cool-but-obscure-unix-tools) :)

**Comment by nmilgalter** [comment]
Where have you been all my life?!
Really good stuff!!

**Comment by vitalipe** [comment]
:)
