### ISSUE TITLE
chmod

### ISSUE THREAD

**Issue by nmilgalter** [tocodeil/unix1-course-examples#87]
?What happen when you do
sudo chmod 777 sudo
current sudo permissions -rwsr-xr-x

**Comment by vitalipe** [comment]
The command ```sudo chmod 777 sudo``` should work just fine, if that's what your'e asking..
But what will happen to sudo after? let's try it: 
```
vitali@Tux:~/tmp$ cp `which sudo` sudo-copy
vitali@Tux:~/tmp$ chmod 777 sudo-copy 
vitali@Tux:~/tmp$ ls -lh sudo-copy 
-rwxrwxrwx 1 vitali vitali 134K ינו 10 08:09 sudo-copy
vitali@Tux:~/tmp$ ./sudo-copy bash
sudo-copy: ./sudo-copy must be owned by uid 0 and have the setuid bit set
```

So it seems like we just "broke" sudo.. but note the 777 means that any logged-in user can alter the content of sudo, which means the it's possible to swap it with a version of ```sudo``` that captures passwords (it still won't "sudo", but it will capture passwords).  

This can be really bad, because hackers are very creative people, and they will find ways to abuse it :)
